version: "3.9"

services:
    laravelapp:
        container_name: laravelapp
        image: kolesnykoleksiy/next-backend-app
        build: .
        ports:
            - "8000:8000"
        env_file:
            -   .env
        depends_on:
            - db
    db:
        container_name: db
        image: postgres
        ports:
            -  "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: bettingdb
        volumes:
            -   pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}

